module.exports = [
  {
    internalAccountId: 21163,
    subcategoryId: 25,
    subcategoryName: "Relief Society",
    unitSubcategoryId: null,
    unitSubcategoryName: null,
    sortOrder: 9,
    budgetAssignedAmount: 4440.0,
    previousActivityAmount: 0.0,
    incomeAmount: 0.0,
    expenseAmount: -4112.25,
    transferAmount: 0.0,
    lines: [
      {
        internalAccountId: 21163,
        subcategoryId: 25,
        subcategoryName: "Relief Society",
        unitSubcategoryId: null,
        unitSubcategoryName: null,
        sortOrder: 9,
        budgetAssignedAmount: 800.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 25,
        subcategoryName: "Relief Society",
        unitSubcategoryId: 869988,
        unitSubcategoryName: "Appreciation Dinner",
        sortOrder: 9,
        budgetAssignedAmount: 250.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 25,
        subcategoryName: "Relief Society",
        unitSubcategoryId: 869989,
        unitSubcategoryName: "Leadership Retreat",
        sortOrder: 9,
        budgetAssignedAmount: 800.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 25,
        subcategoryName: "Relief Society",
        unitSubcategoryId: 870029,
        unitSubcategoryName: "Leadership Meeting",
        sortOrder: 9,
        budgetAssignedAmount: 100.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 25,
        subcategoryName: "Relief Society",
        unitSubcategoryId: 870036,
        unitSubcategoryName: "Stake Womens Conference",
        sortOrder: 9,
        budgetAssignedAmount: 2200.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: -4112.25,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 25,
        subcategoryName: "Relief Society",
        unitSubcategoryId: 870037,
        unitSubcategoryName: "Womens Broadcast",
        sortOrder: 9,
        budgetAssignedAmount: 140.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 25,
        subcategoryName: "Relief Society",
        unitSubcategoryId: 1032543,
        unitSubcategoryName: "Women's Service Project",
        sortOrder: 9,
        budgetAssignedAmount: 150.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      }
    ],
    __typename: "LcrfBudgetSummary"
  }
];
