module.exports = [
  {
    internalAccountId: 21163,
    subcategoryId: 30,
    subcategoryName: "Administration",
    unitSubcategoryId: null,
    unitSubcategoryName: null,
    sortOrder: 2,
    budgetAssignedAmount: 14300.0,
    previousActivityAmount: 0.0,
    incomeAmount: 0.0,
    expenseAmount: -4168.33,
    transferAmount: 0.0,
    lines: [],
    __typename: "LcrfBudgetSummary"
  },
  {
    internalAccountId: 21163,
    subcategoryId: 42,
    subcategoryName: "Curriculum",
    unitSubcategoryId: null,
    unitSubcategoryName: null,
    sortOrder: 3,
    budgetAssignedAmount: 0.0,
    previousActivityAmount: 0.0,
    incomeAmount: 0.0,
    expenseAmount: 0.0,
    transferAmount: 0.0,
    lines: [],
    __typename: "LcrfBudgetSummary"
  },
  {
    internalAccountId: 21163,
    subcategoryId: 32,
    subcategoryName: "Distribution Center Charges",
    unitSubcategoryId: null,
    unitSubcategoryName: null,
    sortOrder: 4,
    budgetAssignedAmount: 0.0,
    previousActivityAmount: 0.0,
    incomeAmount: 0.0,
    expenseAmount: -3140.93,
    transferAmount: 0.0,
    lines: [],
    __typename: "LcrfBudgetSummary"
  },
  {
    internalAccountId: 21163,
    subcategoryId: 22,
    subcategoryName: "Elders Quorum",
    unitSubcategoryId: null,
    unitSubcategoryName: null,
    sortOrder: 5,
    budgetAssignedAmount: 0.0,
    previousActivityAmount: 0.0,
    incomeAmount: 0.0,
    expenseAmount: 0.0,
    transferAmount: 0.0,
    lines: [],
    __typename: "LcrfBudgetSummary"
  },
  {
    internalAccountId: 21163,
    subcategoryId: 43,
    subcategoryName: "Library",
    unitSubcategoryId: null,
    unitSubcategoryName: null,
    sortOrder: 7,
    budgetAssignedAmount: 0.0,
    previousActivityAmount: 0.0,
    incomeAmount: 0.0,
    expenseAmount: 0.0,
    transferAmount: 0.0,
    lines: [],
    __typename: "LcrfBudgetSummary"
  },
  {
    internalAccountId: 21163,
    subcategoryId: 23,
    subcategoryName: "High Priests",
    unitSubcategoryId: null,
    unitSubcategoryName: null,
    sortOrder: 6,
    budgetAssignedAmount: 2500.0,
    previousActivityAmount: 0.0,
    incomeAmount: 0.0,
    expenseAmount: 0.0,
    transferAmount: 0.0,
    lines: [],
    __typename: "LcrfBudgetSummary"
  },
  {
    internalAccountId: 21163,
    subcategoryId: 20,
    subcategoryName: "Primary",
    unitSubcategoryId: null,
    unitSubcategoryName: null,
    sortOrder: 8,
    budgetAssignedAmount: 0.0,
    previousActivityAmount: 0.0,
    incomeAmount: 0.0,
    expenseAmount: 0.0,
    transferAmount: 0.0,
    lines: [],
    __typename: "LcrfBudgetSummary"
  },
  {
    internalAccountId: 21163,
    subcategoryId: 27,
    subcategoryName: "Sunday School",
    unitSubcategoryId: null,
    unitSubcategoryName: null,
    sortOrder: 11,
    budgetAssignedAmount: 400.0,
    previousActivityAmount: 0.0,
    incomeAmount: 0.0,
    expenseAmount: 0.0,
    transferAmount: 0.0,
    lines: [],
    __typename: "LcrfBudgetSummary"
  },
  {
    internalAccountId: 21163,
    subcategoryId: 26,
    subcategoryName: "Single Adults",
    unitSubcategoryId: null,
    unitSubcategoryName: null,
    sortOrder: 10,
    budgetAssignedAmount: 0.0,
    previousActivityAmount: 0.0,
    incomeAmount: 0.0,
    expenseAmount: 0.0,
    transferAmount: 0.0,
    lines: [],
    __typename: "LcrfBudgetSummary"
  },
  {
    internalAccountId: 21163,
    subcategoryId: 21,
    subcategoryName: "Young Men",
    unitSubcategoryId: null,
    unitSubcategoryName: null,
    sortOrder: 12,
    budgetAssignedAmount: 0.0,
    previousActivityAmount: 0.0,
    incomeAmount: 0.0,
    expenseAmount: 0.0,
    transferAmount: 0.0,
    lines: [],
    __typename: "LcrfBudgetSummary"
  },
  {
    internalAccountId: 21163,
    subcategoryId: 24,
    subcategoryName: "Young Women",
    unitSubcategoryId: null,
    unitSubcategoryName: null,
    sortOrder: 13,
    budgetAssignedAmount: 0.0,
    previousActivityAmount: 0.0,
    incomeAmount: 0.0,
    expenseAmount: 0.0,
    transferAmount: 0.0,
    lines: [],
    __typename: "LcrfBudgetSummary"
  },
  {
    internalAccountId: 21163,
    subcategoryId: 25,
    subcategoryName: "Relief Society",
    unitSubcategoryId: null,
    unitSubcategoryName: null,
    sortOrder: 9,
    budgetAssignedAmount: 4440.0,
    previousActivityAmount: 0.0,
    incomeAmount: 0.0,
    expenseAmount: -4112.25,
    transferAmount: 0.0,
    lines: [
      {
        internalAccountId: 21163,
        subcategoryId: 25,
        subcategoryName: "Relief Society",
        unitSubcategoryId: null,
        unitSubcategoryName: null,
        sortOrder: 9,
        budgetAssignedAmount: 800.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 25,
        subcategoryName: "Relief Society",
        unitSubcategoryId: 869988,
        unitSubcategoryName: "Appreciation Dinner",
        sortOrder: 9,
        budgetAssignedAmount: 250.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 25,
        subcategoryName: "Relief Society",
        unitSubcategoryId: 869989,
        unitSubcategoryName: "Leadership Retreat",
        sortOrder: 9,
        budgetAssignedAmount: 800.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 25,
        subcategoryName: "Relief Society",
        unitSubcategoryId: 870029,
        unitSubcategoryName: "Leadership Meeting",
        sortOrder: 9,
        budgetAssignedAmount: 100.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 25,
        subcategoryName: "Relief Society",
        unitSubcategoryId: 870036,
        unitSubcategoryName: "Stake Womens Conference",
        sortOrder: 9,
        budgetAssignedAmount: 2200.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: -4112.25,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 25,
        subcategoryName: "Relief Society",
        unitSubcategoryId: 870037,
        unitSubcategoryName: "Womens Broadcast",
        sortOrder: 9,
        budgetAssignedAmount: 140.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 25,
        subcategoryName: "Relief Society",
        unitSubcategoryId: 1032543,
        unitSubcategoryName: "Women's Service Project",
        sortOrder: 9,
        budgetAssignedAmount: 150.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      }
    ],
    __typename: "LcrfBudgetSummary"
  },
  {
    internalAccountId: 21163,
    subcategoryId: 34,
    subcategoryName: "Miscellaneous",
    unitSubcategoryId: null,
    unitSubcategoryName: null,
    sortOrder: 14,
    budgetAssignedAmount: 3400.0,
    previousActivityAmount: 0.0,
    incomeAmount: 0.0,
    expenseAmount: -681.49,
    transferAmount: 0.0,
    lines: [
      {
        internalAccountId: 21163,
        subcategoryId: 34,
        subcategoryName: "Miscellaneous",
        unitSubcategoryId: null,
        unitSubcategoryName: null,
        sortOrder: 14,
        budgetAssignedAmount: 0.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 34,
        subcategoryName: "Miscellaneous",
        unitSubcategoryId: 869987,
        unitSubcategoryName: "Missionary Conference",
        sortOrder: 14,
        budgetAssignedAmount: 700.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 34,
        subcategoryName: "Miscellaneous",
        unitSubcategoryId: 870035,
        unitSubcategoryName: "RMTC Postage",
        sortOrder: 14,
        budgetAssignedAmount: 100.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 34,
        subcategoryName: "Miscellaneous",
        unitSubcategoryId: 870038,
        unitSubcategoryName: "RMTC Class",
        sortOrder: 14,
        budgetAssignedAmount: 500.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 34,
        subcategoryName: "Miscellaneous",
        unitSubcategoryId: 870039,
        unitSubcategoryName: "RMTC Printing",
        sortOrder: 14,
        budgetAssignedAmount: 100.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 34,
        subcategoryName: "Miscellaneous",
        unitSubcategoryId: 1055202,
        unitSubcategoryName: "ERM Class",
        sortOrder: 14,
        budgetAssignedAmount: 500.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 34,
        subcategoryName: "Miscellaneous",
        unitSubcategoryId: 1092240,
        unitSubcategoryName: "Self Reliance Class",
        sortOrder: 14,
        budgetAssignedAmount: 1500.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: -681.49,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      }
    ],
    __typename: "LcrfBudgetSummary"
  },
  {
    internalAccountId: 21163,
    subcategoryId: 315,
    subcategoryName: "Activities",
    unitSubcategoryId: null,
    unitSubcategoryName: null,
    sortOrder: 16,
    budgetAssignedAmount: 48900.0,
    previousActivityAmount: 0.0,
    incomeAmount: 0.0,
    expenseAmount: -4277.29,
    transferAmount: 0.0,
    lines: [
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: null,
        unitSubcategoryName: null,
        sortOrder: 16,
        budgetAssignedAmount: 0.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 532306,
        unitSubcategoryName: "Institute Munch & Mingle",
        sortOrder: 16,
        budgetAssignedAmount: 6000.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: -545.76,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 577276,
        unitSubcategoryName: "Halloween Dance",
        sortOrder: 16,
        budgetAssignedAmount: 2000.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 580190,
        unitSubcategoryName: "Priesthood and Pancakes",
        sortOrder: 16,
        budgetAssignedAmount: 400.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 597631,
        unitSubcategoryName: "Institute Opening Social",
        sortOrder: 16,
        budgetAssignedAmount: 3500.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: -538.67,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 731747,
        unitSubcategoryName: "HS Grad Welcome Activity",
        sortOrder: 16,
        budgetAssignedAmount: 2000.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 731749,
        unitSubcategoryName: "Lehi Roundup",
        sortOrder: 16,
        budgetAssignedAmount: 3500.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 731754,
        unitSubcategoryName: "Devotional Munch and Mingle",
        sortOrder: 16,
        budgetAssignedAmount: 0.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: -858.7,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 870397,
        unitSubcategoryName: "25+ Activities",
        sortOrder: 16,
        budgetAssignedAmount: 2400.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 970373,
        unitSubcategoryName: "Stake Munch & Mingle",
        sortOrder: 16,
        budgetAssignedAmount: 3000.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 970374,
        unitSubcategoryName: "Stake FHE",
        sortOrder: 16,
        budgetAssignedAmount: 2400.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: -167.64,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 1006577,
        unitSubcategoryName: "Stake Choir",
        sortOrder: 16,
        budgetAssignedAmount: 250.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 1055203,
        unitSubcategoryName: "Stake Leadership Dinner",
        sortOrder: 16,
        budgetAssignedAmount: 750.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 1061014,
        unitSubcategoryName: "Dance/Winter Ball",
        sortOrder: 16,
        budgetAssignedAmount: 1000.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 1061018,
        unitSubcategoryName: "Ice Skating",
        sortOrder: 16,
        budgetAssignedAmount: 1200.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 1061019,
        unitSubcategoryName: "Easter Activity",
        sortOrder: 16,
        budgetAssignedAmount: 600.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 1061021,
        unitSubcategoryName: "Pool Party",
        sortOrder: 16,
        budgetAssignedAmount: 600.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 1061022,
        unitSubcategoryName: "March Madness Game Night",
        sortOrder: 16,
        budgetAssignedAmount: 500.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 1061023,
        unitSubcategoryName: "Drive-in Movie",
        sortOrder: 16,
        budgetAssignedAmount: 2000.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 1061025,
        unitSubcategoryName: "Vivian Park Activity",
        sortOrder: 16,
        budgetAssignedAmount: 1500.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 1061026,
        unitSubcategoryName: "Christmas Lights",
        sortOrder: 16,
        budgetAssignedAmount: 500.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 1061027,
        unitSubcategoryName: "Auction/Food Drive",
        sortOrder: 16,
        budgetAssignedAmount: 1000.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 1079168,
        unitSubcategoryName: "Multi",
        sortOrder: 16,
        budgetAssignedAmount: 1200.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: -600.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 1079169,
        unitSubcategoryName: "Conventional Stake Donations",
        sortOrder: 16,
        budgetAssignedAmount: 0.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 1085172,
        unitSubcategoryName: "Stake Sports",
        sortOrder: 16,
        budgetAssignedAmount: 600.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 1087001,
        unitSubcategoryName: "AFY",
        sortOrder: 16,
        budgetAssignedAmount: 12000.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 1144476,
        unitSubcategoryName: "Family History",
        sortOrder: 16,
        budgetAssignedAmount: 0.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: 0.0,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      },
      {
        internalAccountId: 21163,
        subcategoryId: 315,
        subcategoryName: "Activities",
        unitSubcategoryId: 1163861,
        unitSubcategoryName: "Monthly Stake Activity",
        sortOrder: 16,
        budgetAssignedAmount: 0.0,
        previousActivityAmount: 0.0,
        incomeAmount: 0.0,
        expenseAmount: -1566.52,
        transferAmount: 0.0,
        __typename: "LcrfBudgetSummary"
      }
    ],
    __typename: "LcrfBudgetSummary"
  }
];
